<?php $_orders = $block->getSubscrib(); ?>

<?php if ($_orders && count($_orders)) : ?>

    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id">Order #</th>
                    <th scope="col" class="col subscriptionid">Subscription ID</th>
                    <th scope="col" class="col product">Product</th>
                
                    <th scope="col" class="col nextcharged">Next Charged At</th>
                    
                    <th scope="col" class="col status">Status</th>
                    <th scope="col" class="col actions">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getSubscrib() as $_order) : ?>
<tr>
                  <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $_order->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Subscription ID')) ?>" class="col subscriptionid">
            <a href="<?php echo $block->getSubscribUrl($_order);?>"> <?php echo $_order->getSubscriptionId() ?></a></td>

                <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="col product">
                <?php echo $_order->getValue() ?>
            </td> <td data-th="<?= $block->escapeHtml(__('Next Charged At')) ?>" class="col nextcharged">
                <?php echo $_order->getNextChargeAt() ?>
            </td>
             <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                <?php echo $_order->getStatus() ?>
            </td> 
            <td data-th="<?= $block->escapeHtml(__('View')) ?>" class="col actions">
                <?php echo "View"; ?>
            </td>
</tr>
                    <?php endforeach; ?>      
                    
                          </tbody>
        </table>
</div>
<?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
        <?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have not yet subscribed for any product.')) ?></span></div>
<?php endif ?>