<?php
$subscriptionHelper = $this->helper(\Razorpay\Subscription\Helper\Subscription::class);

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->getProduct()->getRazorpaySubscriptionEnabled() && $subscriptionHelper->isSubscriptionActive()): ?>
            <style>
                .isHidden {
                    display: none; /* hide radio buttons */
                }

                .plan-label {
                    display: inline-block;
                    width: 397px;
                    height: 77px;
                }

                .radio:checked + .plan-label {   /* target next sibling (+) label */
                    background-color: #f0efef;
                    border-radius: 10px;
                }

            </style>
            <div class="subscription-data" style="display: block;padding-bottom: 50px;">

                <?php if($block->getProduct()->getRazorpaySubscriptionMode() == "withSubscription"): ?>
                    <div class="control" style="margin-top: 30px;">
                        <input style="margin-bottom: 20px;"
                               type="radio" checked
                               class="radio required-entry validate-one-required-by-name"
                               name="paymentOption"
                               data-validate="{'validate-one-required-by-name':true}"
                               value="oneTime"
                               ifnot="method.error_message"
                               ko-checked="element.isSelected"
                               ko-value="method.carrier_code + '_' + method.method_code"
                               attr="'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,'checked': element.rates().length == 1 || element.isSelected"
                        ><?php /* @escapeNotVerified */echo __(" One Time Payment") ?> </input><br>
                        <input type="radio"
                               class="radio required-entry validate-one-required-by-name"
                               name="paymentOption"
                               data-validate="{'validate-one-required-by-name':true}"
                               value="subscription"
                               ifnot="method.error_message"
                               ko-checked="element.isSelected"
                               ko-value="method.carrier_code + '_' + method.method_code"
                               attr="'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,'checked': element.rates().length == 1 || element.isSelected"
                        ><?php /* @escapeNotVerified */echo __("Subscribe to this product") ?></input>
                    </div>
                    <?php echo $this->getLayout()->createBlock("Razorpay\Subscription\Block\Product\AddToCartProductOptionView")->setTemplate("Razorpay_Subscription::product/subscription_options.phtml")->setData("product_id",$block->getProduct()->getId())->toHtml() ?>
                <?php elseif($block->getProduct()->getRazorpaySubscriptionMode() == "subscriptionOnly"): ?>
                    <input type="hidden" value="subscription" name="paymentOption">
                    <?php echo $this->getLayout()->createBlock("Razorpay\Subscription\Block\Product\AddToCartProductOptionView")->setTemplate("Razorpay_Subscription::product/subscription_options.phtml")->setData("product_id",$block->getProduct()->getId())->toHtml() ?>
                <?php endif; ?>

            </div>
        <?php endif; ?>

        <br>
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                        echo __('Qty') ?></span></label>
                <div class="control">
                    <input type="number"
                           name="qty"
                           id="qty"
                           maxlength="12"
                           value="<?php /* @escapeNotVerified */
                           echo $block->getProductDefaultQty() * 1 ?>"
                           title="<?php /* @escapeNotVerified */
                           echo __('Qty') ?>" class="input-text qty"
                           data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                    />
                </div>
            </div>

        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */
                    echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */
                    echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "catalogAddToCart": {
                    "bindSubmit": false
                }
            }
        }
    </script>
<?php endif; ?>
<script type="text/javascript">

    require([
        'jquery',
        'jquery/ui',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'

    ], function ($) {
        'use strict';

        <?php if($block->getProduct()->getRazorpaySubscriptionMode() == "withSubscription"): ?>
        $(".subscription-option-wrapper").hide();
        <?php endif; ?>

        $(document).on('change', 'input[type="radio"]', function () {
            const paymentOptionType = $("input[name='paymentOption']:checked").val();
            if (paymentOptionType.trim() == 'oneTime') {
                $(".subscription-option-wrapper").hide();
                // $('.price').text($('#productOriginalPrice').val());
                $("input[name='plan_id']:checked").prop('checked', false);

            }
            if (paymentOptionType.trim() == 'subscription') {
                $(".subscription-option-wrapper").show();
            }
        });

        $('input[type=radio][name="plan_id"]').change(function() {
            let planType = $("input[name='plan_id']:checked").prev().val();
            let price = $('#frequencyPrice_'+planType).val();
            $('.price').text(price);
        })
    });
</script>
