<?php /** @var Razorpay\Subscription\Block\Display $block */ ?>

<?php $_orders = $block->getSubscribs(); ?>

<?php if ($_orders && count($_orders)) : ?>
  <form id="action-form" method="post">
    <div class="table-wrapper orders-history">
        <div class="field region">
            <select class="action-select">
                <option>--Action--</option>   
                <option value="pause">Pause</option>
                <option value="resume">Resume</option>
            </select>
        
        </div> 
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><lable><input type="checkbox" id="select-all"></lable></th>
                <th scope="col" class="col id">Order #</th>
                <th scope="col" class="col subscriptionid">Subscription ID</th>
                <th scope="col" class="col product">Product</th>
                <th scope="col" class="col status">Status</th>
                <th scope="col" class="col nextcharged">Next Charged At</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getSubscribs() as $_order) : ?>
                <?php /** @var Razorpay\Subscription\Model\Subscrib */ ?>
                <tr>
                    <td>
                       <lable><input type="checkbox" name="orders[]" class="checkbox_select" value="<?= $_order->getId() ?>"></lable>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                        <?php echo $_order->getId() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Subscription ID')) ?>" class="col subscriptionid">
                        <a href="<?php echo $block->getSubscribUrl($_order); ?>"> <?php echo $_order->getSubscriptionId() ?></a>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="col product">
                        <?php echo $_order->getValue() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                        <?php echo $_order->getStatus() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Next Charged At')) ?>" class="col nextcharged">
                        <?php echo $_order->getNextChargeAt() ?>
                    </td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
    </div>
</form>    
<?php else: ?>
    <div class="message info empty">
        <span><?php echo __("You do not have any subscriptions yet."); ?></span>
    </div>
<?php endif ?>
<script>
    require([
        "jquery"
    ],
     function($){
        var selectAll = $('#select-all')
        var actionSelect = $('.action-select')
        var dataform = $('#action-form')

        selectAll.click(function(){
            $('.checkbox_select').prop('checked',$(this).prop('checked'))
        })
       
        actionSelect.on('change', function(){
          if(this.value == "pause" || this.value == "active" || this.value == "resume"){
             switch (this.value) {
                 case "cancel":
                     //console.log('Hello1')
                     break;
                
                case "resume":
                    //console.log('Hello2')
                    break;

                case "pause":
                    dataform.attr('action',"<?php echo $block->getUrl('razorpaysubscription/customer/massPauseSubscription') ?>")
                    break;    
             }
            if($('.checkbox_select').is(':checked')){ 
                dataform.submit();
            }else{
              console.log('You havent selected any subscription !')  
            }  
           }
        })
     })
</script>
