<?php /** @var Razorpay\Subscription\Block\View $block */ ?>

<?php
$subscriptioninfo = $block->getSubscrib();
?>

<div class="block block-dashboard-info">
    <div class="block-title"><strong>Order # <?php echo $subscriptioninfo['entity_id']; ?></strong>
        <a href="<?php echo $block->getUrl('razorpaysubscription/customer/cancelSubscription/'); ?>s_id/<?php echo $subscriptioninfo['subscription_id']; ?>/oid/<?php echo $subscriptioninfo['entity_id']; ?>"
           class="action primary"
           style="float:right;" <?php if ($subscriptioninfo['status'] == 'cancelled') echo 'disabled'; ?> >Cancel</a>
        <a href="<?php echo $block->getUrl('razorpaysubscription/customer/cancelSubscription/'); ?>s_id/<?php echo $subscriptioninfo['subscription_id']; ?>/oid/<?php echo $subscriptioninfo['entity_id']; ?>"
           class="action primary" style="float:right;">Upgrade</a>
    </div>
    <div class="block-content">
        <div class="box box-information ">
            <strong class="box-title">
                <span>Product Info</span>
            </strong>
            <span class="delimiter"></span>
            <div class="box-content">
                <strong class="account">
                    Product Name :
                </strong> <?php echo $subscriptioninfo['value']; ?>
                <span class="delimiter"></span>
            </div>

            <div class="box-content delimiter">
                <strong class="account ">
                    SKU :
                </strong> <?php echo $subscriptioninfo['sku']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Total Count :
                </strong> <?php echo $subscriptioninfo['total_count']; ?>
            </div>
        </div>
        <div class="box box-newsletter">
            <strong class="box-title">
                <span>Payment Schedule</span>
            </strong>
            <div class="box-content">
                <strong class="account">
                    Subscription ID :
                </strong> <?php echo $subscriptioninfo['subscription_id']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Status :
                </strong> <?php echo ucfirst($subscriptioninfo['status']); ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Recurring Start Date :
                </strong> <?php echo $subscriptioninfo['start_at']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Next Charge Date :
                </strong> <?php echo $subscriptioninfo['next_charge_at']; ?>
            </div>
        </div>
    </div>
</div>
