<?php /** @var Razorpay\Subscription\Block\View $block */ ?>

<?php
$subscriptioninfo = $block->getSubscrib();
$invoices = $block->getSubscriptionInvoice();
?>

<div class="block block-dashboard-info">
    <div class="block-title"><strong>Order # <?php echo $subscriptioninfo['entity_id']; ?></strong>
        <?php if ($subscriptioninfo['status'] != 'cancelled' && $subscriptioninfo['status'] != 'created'): ?>
            <a href="<?php echo $block->getUrl('razorpaysubscription/customer/cancelSubscription/'); ?>s_id/<?php echo $subscriptioninfo['subscription_id']; ?>/oid/<?php echo $subscriptioninfo['entity_id']; ?>"
               class="action primary"
               style="float:right;"  >Cancel</a>

          <?php if ($subscriptioninfo['status'] != 'paused'): ?>
            <a href="<?php echo $block->getUrl('razorpaysubscription/customer/pauseSubscription/'); ?>s_id/<?php echo $subscriptioninfo['subscription_id']; ?>/oid/<?php echo $subscriptioninfo['entity_id']; ?>"
               class="action primary"
               style="float:right;"  >Pause</a>
          <?php endif ?>
         
          <?php if ($subscriptioninfo['status'] != 'active'): ?> 
            <a href="<?php echo $block->getUrl('razorpaysubscription/customer/resumeSubscription/'); ?>s_id/<?php echo $subscriptioninfo['subscription_id']; ?>/oid/<?php echo $subscriptioninfo['entity_id']; ?>"
               class="action primary"
               style="float:right;"  >Resume</a>
          <?php endif ?>     
        <?php endif ?>
<!--        <a href="--><?php //echo $block->getUrl(''); ?><!--s_id/--><?php //echo $subscriptioninfo['subscription_id']; ?><!--/oid/--><?php //echo $subscriptioninfo['entity_id']; ?><!--"-->
<!--           class="action primary" style="float:right;">Upgrade</a>-->
    </div>
    <div class="block-content">
        <div class="box box-information ">
            <strong class="box-title">
                <span>Product Info</span>
            </strong>
            <span class="delimiter"></span>
            <div class="box-content">
                <strong class="account">
                    Customer Id :
                </strong> <?php echo $subscriptioninfo['razorpay_customer_id']; ?>
                <span class="delimiter"></span>
            </div>
            <div class="box-content">
                <strong class="account">
                    Product Name :
                </strong> <?php echo $subscriptioninfo['value']; ?>
                <span class="delimiter"></span>
            </div>

            <div class="box-content delimiter">
                <strong class="account ">
                    SKU :
                </strong> <?php echo $subscriptioninfo['sku']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Total Count :
                </strong> <?php echo $subscriptioninfo['total_count']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Qty :
                </strong> <?php echo (int)$subscriptioninfo['total_qty']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Amount :
                </strong> <?php echo $block->getCurrencySymbol($subscriptioninfo['store_currency_code'])." ".$subscriptioninfo['subtotal']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Shipping :
                </strong> <?php echo $block->getCurrencySymbol($subscriptioninfo['store_currency_code'])." ".$subscriptioninfo['base_shipping_amount']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Grand Total :
                </strong> <?php echo $block->getCurrencySymbol($subscriptioninfo['store_currency_code'])." ".$subscriptioninfo['grand_total']; ?>
            </div>
        </div>
        <div class="box box-newsletter">
            <strong class="box-title">
                <span>Payment Schedule</span>
            </strong>
            <div class="box-content">
                <strong class="account">
                    Subscription ID :
                </strong> <?php echo $subscriptioninfo['subscription_id']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Status :
                </strong> <?php echo ucfirst($subscriptioninfo['status']); ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Recurring Start Date :
                </strong> <?php echo $subscriptioninfo['start_at']; ?>
            </div>
            <div class="box-content">
                <strong class="account">
                    Next Charge Date :
                </strong> <?php echo $subscriptioninfo['next_charge_at']; ?>
            </div>
        </div>
    </div>
    <br/><br/>
    <div class="block-content">
        <strong class="box-title">
            <span>Plan Info</span>
        </strong>
        <span class="delimiter"></span>
        <div class="box-content">
            <strong class="account">
                Plan Name :
            </strong> <?php echo $subscriptioninfo['plan_name']; ?>
            <span class="delimiter"></span>
        </div>
        <div class="box-content">
            <strong class="account">
                Plan id :
            </strong> <?php echo $subscriptioninfo['plan_id']; ?>
            <span class="delimiter"></span>
        </div>
        <div class="box-content">
            <strong class="account">
                Billing frequency:
            </strong> <?php echo $subscriptioninfo['plan_type']; ?>
            <span class="delimiter"></span>
        </div>
            <div class="box-content">
            <strong class="account">
                Billing amount :
                </strong> <?php echo $block->getCurrencySymbol($subscriptioninfo['store_currency_code'])." ".$subscriptioninfo['subtotal']; ?>
            </div>
    </div>
    <br/><br/>
     
    <?php /** invoice table */ if ($invoices && count($invoices['items'])) : ?>
        <div class="table-wrapper orders-recent">
            <table class="data table table-order-items recent" id="my-orders-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Recent Orders')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                        <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Invoice Id')) ?></th>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Recurring Amount')) ?></th>
                        <th scope="col" class="col actions"><?= $block->escapeHtml(__('Add-Ons')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col actions"><?= $block->escapeHtml(__('Total amount')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (($subscriptioninfo['next_charge_at'] != $subscriptioninfo['end_at']) && ($subscriptioninfo['status'] !="cancelled") && ($subscriptioninfo['status'] !="created")) : ?>  
                        <tr>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= !empty($invoices['items'][0]['billing_end']) ? date('M d, Y', $invoices['items'][0]['billing_end']): '--'?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Invoice Id')) ?>" class="col invoice">--</td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Recurring Amount')) ?>" class="col recurring"><?= $block->getCurrencySymbol($subscriptioninfo['store_currency_code'])." ".$invoices['items'][0]['line_items'][0]['net_amount']/100; ?>
                                   <br/><small><?= $invoices['items'][0]['line_items'][0]['quantity'] ."x ".$block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoices['items'][0]['line_items'][0]['unit_amount']/100;  ?> per unit</small>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Add-Ons')) ?>" class="col addon">--</td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status"><?= 'Next Due' ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Total amount')) ?>" class="col total"><?= $block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoices['items'][0]['amount_paid']/100 ?></td>
                            </tr>
                    <?php endif ?>
                    <?php foreach ($invoices['items'] as $invoice) : ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?=  !empty($invoice['billing_start']) ? date('M d, Y', $invoice['billing_start']) : '--' ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Invoice Id')) ?>" class="col invoice"><a href="<?= $invoice['short_url'] ?>" target="_blank"><?php echo $invoice['id'] ?></a></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Recurring Amount')) ?>" class="col recurring"><?php echo $block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoice['line_items'][0]['net_amount']/100; ?>
                                   <br/><small><?php echo $invoice['line_items'][0]['quantity'] ."x ".$block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoice['line_items'][0]['unit_amount']/100  ?> per unit</small>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Add-Ons')) ?>" class="col addon"><?= isset($invoice['line_items'][1]) ? $invoice['line_items'][1]['name']."<br/>".$block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoice['line_items'][1]['net_amount']/100 : '--'?>
                                <?php if (isset($invoice['line_items'][1])) :?>
                                   <br/> <small><?php echo $invoice['line_items'][1]['quantity'] ."x ".$block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoice['line_items'][1]['unit_amount']/100  ?> per unit</small>
                                <?php endif ?>
                                </td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status"><?= ucfirst($invoice['status']) ?></td>
                                <td data-th="<?= $block->escapeHtmlAttr(__('Total amount')) ?>" class="col total"><?= $block->getCurrencySymbol($subscriptioninfo['store_currency_code']).$invoice['amount']/100 ?></td>
                            </tr>
                        <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</div>
