<?php
/**
 * @var $block \Razorpay\Subscription\Controller\Adminhtml\OrderDetails\SubscriptionOrderDetails
 */

$subscriptionDetails = $block->fetchSubscriptionOrderDetails();

?>
<?php if (!empty($subscriptionDetails)): ?>
    <section class="admin__page-section order-view-susbcription-details">
        <div>
            <div class="admin__page-section-title">
                <span class="title">Subscription Details</span>
            </div>
            <div class="admin__page-section-content">
                <strong>Subscription Type:</strong>
                <span class="price"><?php echo __(ucfirst($subscriptionDetails["plan_type"])) ?></span>
            </div>
            <div class="admin__page-section-content">
                <strong>Subscription Id:</strong>
                <span class="actions"><a href="<?php echo $block->getUrl('subscribed/subscription/edit/'); ?>"><?php echo __($subscriptionDetails["entity_id"]) ?></a></span>
            </div>
        </div>
    </section>
<?php endif; ?>

