<?php /**
       * @var Razorpay\Subscription\Block\View $block 
       */ ?>

<?php
$subscriptionInfo = $block->getSubscrib();
$invoices = $block->getSubscriptionInvoice();
?>
<div class="page-main-actions">
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="">
            <div class="page-actions-buttons">
                <button id="back" title="Back" type="button" class="action-default scalable back" onclick="location.href = '<?php echo $block->getUrl('*'); ?>'">
                    <span>Back</span>
                </button>
                <?php
                if ($subscriptionInfo['status'] != 'cancelled' && $subscriptionInfo['status'] != 'created' && $subscriptionInfo['status'] != 'authenticated') :

                    if ($subscriptionInfo['status'] != 'paused') : ?>
                        <button id="pause" title="Pause" type="button" class="action-default scalable" onclick="location.href = '<?php echo $block->getUrl('subscribed/subscription/pause/'); ?>subscription_id/<?php echo $subscriptionInfo['subscription_id']; ?>/id/<?php echo $subscriptionInfo['entity_id']; ?>'">
                            <span>Pause</span>
                        </button>
                    <?php endif ?>

                    <?php if ($subscriptionInfo['status'] != 'active') : ?>
                    <button id="resume" title="Resume" type="button" class="action-default scalable" onclick="location.href = '<?php echo $block->getUrl('subscribed/subscription/resume/'); ?>subscription_id/<?php echo $subscriptionInfo['subscription_id']; ?>/id/<?php echo $subscriptionInfo['entity_id']; ?>'">
                        <span>Resume</span>
                    </button>
                    <?php endif ?>

                    <button id="cancel" title="Cancel" type="button" class="action-default scalable" onclick="confirm('Are you sure you want to Cancel Subscription?', '<?php echo $block->getUrl('subscribed/subscription/cancel/'); ?>subscription_id/<?php echo $subscriptionInfo['subscription_id']; ?>/id/<?php echo $subscriptionInfo['entity_id']; ?>')">
                        <span>Cancel</span>
                    </button>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>

<div class="admin__scope-old">
    <div class="fieldset-wrapper subscription-information">
        <div class="fieldset-wrapper-title">
            <span class="title">Subscription Information</span>
        </div>
        <table class="admin__table-secondary">
            <tbody>
            <tr>
                <th>Subscription Id</th>
                <td><?php echo $subscriptionInfo['subscription_id']; ?></td>
            </tr>
            <tr>
                <th>Customer Id</th>
                <td><?php echo $subscriptionInfo['razorpay_customer_id']; ?></td>
            </tr>
            <tr>
                <th>Plan Id</th>
                <td><?php echo $subscriptionInfo['plan_id']; ?></td>
            </tr>
            <tr>
                <th>Plan Name</th>
                <td><?php echo $subscriptionInfo['plan_name']; ?></td>
            </tr>
            <tr>
                <th>Billing Frequency</th>
                <td><?php echo $subscriptionInfo['plan_type']; ?></td>
            </tr>
            <tr>
                <th>Product name</th>
                <td><?php echo $subscriptionInfo['value']; ?></td>
            </tr>
            <tr>
                <th>Amount</th>
                <td><?php echo $block->getCurrencySymbol($subscriptionInfo['store_currency_code'])." ".$subscriptionInfo['subtotal']; ?></td>
            </tr>
            <tr>
                <th>Shipping</th>
                <td><?php echo $block->getCurrencySymbol($subscriptionInfo['store_currency_code'])." ".$subscriptionInfo['base_shipping_amount']; ?></td>
            </tr>
            <tr>
                <th>Grand Total</th>
                <td><?php echo $block->getCurrencySymbol($subscriptionInfo['store_currency_code'])." ".$subscriptionInfo['grand_total']; ?></td>
            </tr>
            <tr>
                <th>Total Count</th>
                <td><?php echo $subscriptionInfo['total_count']; ?></td>
            </tr>
            <tr>
                <th>Paid Count</th>
                <td><?php echo $subscriptionInfo['paid_count']; ?></td>
            </tr>
            <tr>
                <th>Status</th>
                <td><?php echo $subscriptionInfo['status']; ?></td>
            </tr>
            <tr>
                <th>Created At</th>
                <td><?php echo $subscriptionInfo['subscription_created_at']; ?></td>
            </tr>
            <tr>
                <th>Next Charge At</th>
                <td><?php echo $subscriptionInfo['next_charge_at']; ?></td>
            </tr>
            <tr>
                <th>Start At</th>
                <td><?php echo $subscriptionInfo['start_at']; ?></td>
            </tr>
            <tr>
                <th>End At</th>
                <td><?php echo $subscriptionInfo['end_at']; ?></td>
            </tr>
            </tbody>
        </table>
    </div>


    <?php if ($invoices && count($invoices['items'])) : ?>
        <div class="fieldset-wrapper subscription-invoices">

            <div class="fieldset-wrapper-title">
                <span class="title">Invoices Detail</span>
            </div>

            <div class="table-wrapper orders-recent">
                <table class="data-grid" id="invoice-table">
                    <thead>
                    <tr>
                        <th class="data-grid-th"><?php echo $block->escapeHtml(__('Invoice Id')) ?></th>
                        <th class="data-grid-th"><?php echo $block->escapeHtml(__('Recurring Amount')) ?></th>
                        <th class="data-grid-th"><?php echo $block->escapeHtml(__('Add-Ons')) ?></th>
                        <th class="data-grid-th"><?php echo $block->escapeHtml(__('Total amount')) ?></th>
                        <th class="data-grid-th"><?php echo $block->escapeHtml(__('Status')) ?></th>
                        <th class="data-grid-th"><?php echo $block->escapeHtml(__('Date')) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (($subscriptionInfo['next_charge_at'] != $subscriptionInfo['end_at']) && ($subscriptionInfo['status'] !="cancelled") && ($subscriptionInfo['status'] !="created")) : ?>
                        <tr>
                            <td>--</td>
                            <td><?php echo $invoices['items'][0]['currency_symbol']." ".$invoices['items'][0]['line_items'][0]['net_amount']/100; ?>
                                <br/><small><?php echo $invoices['items'][0]['line_items'][0]['quantity'] ."x ".$invoices['items'][0]['currency_symbol'].$invoices['items'][0]['line_items'][0]['unit_amount']/100;  ?> per unit</small>
                            </td>
                            <td>--</td>
                            <td><?php echo $invoices['items'][0]['currency_symbol'].$invoices['items'][0]['line_items'][0]['net_amount']/100 ?></td>
                            <td><?php echo 'Next Due' ?></td>
                            <td><?php echo !empty($invoices['items'][0]['billing_end']) ? date('M d, Y', $invoices['items'][0]['billing_end']): '--'?></td>
                        </tr>
                    <?php endif ?>
                    <?php foreach ($invoices['items'] as $invoice) : ?>
                        <tr>
                            <td><a href="<?php echo $invoice['short_url'] ?>" target="_blank"><?php echo $invoice['id'] ?></a></td>
                            <td><?php echo $invoice['currency_symbol'].$invoice['line_items'][0]['net_amount']/100; ?>
                                <br/><small><?php echo $invoice['line_items'][0]['quantity'] ."x ".$invoice['currency_symbol'].$invoice['line_items'][0]['unit_amount']/100  ?> per unit</small>
                            </td>
                            <td><?php echo isset($invoice['line_items'][1]) ? $invoice['line_items'][1]['name']."<br/>".$invoice['currency_symbol'].$invoice['line_items'][1]['net_amount']/100 : '--'?>
                                <?php if (isset($invoice['line_items'][1])) :?>
                                    <br/> <small><?php echo $invoice['line_items'][1]['quantity'] ."x ".$invoice['currency_symbol'].$invoice['line_items'][1]['unit_amount']/100  ?> per unit</small>
                                <?php endif ?>
                            </td>
                            <td><?php echo $invoice['currency_symbol'].$invoice['amount']/100 ?></td>
                            <td><?php echo ucfirst($invoice['status']) ?></td>
                            <td><?php echo  !empty($invoice['billing_start']) ? date('M d, Y', $invoice['billing_start']) : '--' ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif ?>

</div>